android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=384m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=4
org.gradle.configuration-cache=false
org.gradle.configureondemand=false
