android.useAndroidX=true
android.enableJetifier=false
android.aapt2FromMavenOverride=/opt/android-sdk/build-tools/35.0.1/aapt2
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=384m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=6
org.gradle.configuration-cache=false
org.gradle.configureondemand=false
