name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: 35.0.1

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Kill Java Processes
        run: pkill -9 java || true

      - name: Clean Flutter & Gradle
        run: |
          flutter clean
          rm -rf build/
          rm -rf .dart_tool/
          rm -rf pubspec.lock
          rm -rf android/.gradle/
          rm -rf android/build/

      - name: Copy gradle.properties untuk GitHub Actions
        run: cp android/gradle.properties.github android/gradle.properties

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: zqwis-release
          path: build/app/outputs/flutter-apk/app-release.apk